import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RootProvider from "./context";
import { Toaster } from "@/components/ui/toaster";
import "./styles/ag-grid-custom.css";

const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "Accountable.ai",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased font-noto`}
         >
            <RootProvider>
               <div>{children}</div>
               <Toaster />
            </RootProvider>
         </body>
      </html>
   );
}
